name: EnhancedFindDialogCITestPrBuild
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  Compile_addon:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install system dependencies
        run: sudo apt install gettext
      - name: Install python
        uses: actions/setup-python@v4
        with:
          # it seems that x86 versions of python 3 are not available for linux install.
          # In this addon context it is really not important, as packaging should not deppend on architecture versions
          # However, for future NVDA related actions we might have to switch to windows runners
          python-version: "3.11"
      - name: install python dependencies
        run: |
          pip install scons
          pip install markdown
      - name: generate addon
        run: |
          rm -f *.nvda-addon || true
          scons
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: addon
          path: "*.nvda-addon"
